### ISSUE TITLE
$this->template_path is wrong

### ISSUE THREAD

**Issue by gregghenry** [spivurno/gfur-activate-template#1]
I was having an issue with the activate.php file with the `get_template_part()` calls. The theme name is getting included in the `$this->template_folder` variable so every `get_template_part()` was failing.

**Comment by spivurno** [comment]
Hi Greg, the class assumes that all the files will be in a folder in the theme. The folder name does not matter so long as they are in a folder. You can override the "template_folder" location on line 7 of activate.php. Change this line:

```
$gw_activate_template = new GWActivateTemplate();
```

To this:

```
$gw_activate_template = new GWActivateTemplate( array( 
    'template_folder' => '' 
} );
```

**Comment by gregghenry** [comment]
I had them in a folder and it still gave me that error. I resolved my issue by adjusting the get_template_part, but will look into that change if I have time. Thanks for the reply.

**Comment by spivurno** [comment]
I tested locally and with the files in a folder within the theme folder, it is working as expected. If you're able to recreate your issue and would like to share access to the site with me so I can take a look, feel free to email the WP and FTP logins to david [at] gravitywiz [dot] com.

**Comment by gregghenry** [comment]
hmm. maybe its just my setup on this particular site. It's pretty customized. I didnt test on a fresh install so I'm going to close. Thanks for being quick and testing.
