### ISSUE TITLE
Break theme design with child theme

### ISSUE THREAD

**Issue by lekiend** [spivurno/gfur-activate-template#2]
Hello,

Is this up to date ?
I use Avada-child-theme and the design with gf user registration activation messages is a mess.
It looks like css are not applied.

Regards

**Comment by spivurno** [comment]
Some themes do not load their CSS in a way that is standard to WordPress. You can modify the template as desired to include your theme's CSS.

**Comment by lekiend** [comment]
It is not only a css issue, a lot af things included in the theme are not loaded in activate.php like fontawesome, dynamic css, etc...

**Comment by spivurno** [comment]
The activate.php template calls the get_header() and get_footer() method which should be the only requirements for a theme to load it's dependencies. Unfortunately, we don't have the throughput to modify this to work with every theme out-of-the-box. If the theme is doing things "the WordPress way" it should just work. Otherwise, the template is designed to be modified as needed.

**Comment by lekiend** [comment]
Same issue for someone else on your discussion feed here: [https://gravitywiz.com/customizing-gravity-forms-user-registration-activation-page/comment-page-6/#comment-281708](https://gravitywiz.com/customizing-gravity-forms-user-registration-activation-page/comment-page-6/#comment-281708)

**Comment by lekiend** [comment]
I replaced your code to include in functions.php with the following code and it works perfectly with my theme.
`/* Override Gravity Forms activate.php template */
add_filter( 'template_include', 'activation_page' );
function activation_page( $template ) {
	$is_activation_page = isset( $_GET['page'] ) && $_GET['page'] == 'gf_activation';
	if ( !$is_activation_page ) {
		return $template;
	}
	$template_path = locate_template('activate.php');
	if ( empty($template_path) ) {
		return $template;
	}
	$template = $template_path;
	return $template;
}`

**Comment by spivurno** [comment]
If you're a [Gravity Perks](http://gravityperks.com) customer, we'll be happy to provide additional support via the [support form](http://gravitywiz.com/support/).

**Comment by lekiend** [comment]
I see that you have an easy to use plugin https://gravitywiz.com/documentation/gravity-forms-better-user-activation/.
Did you try it with [AVADA theme](https://themeforest.net/item/avada-responsive-multipurpose-theme/2833226) (used by more than 400,000 people) ?
I'd like to be sure it will work before buying it.
Thank you

**Comment by spivurno** [comment]
Hi Lekiend, I have not personally tested it; however, if you find there is a conflict, I'll be happy to take a look via support. 🙂

**Comment by lekiend** [comment]
And is it compatible with WPML ?

**Comment by spivurno** [comment]
Also untested. We do have a lot of users using WPML though so there is a good chance it "just works". If not, we'll be happy to add support.

**Comment by lekiend** [comment]
Your plugin do not work with AVADA theme :-(.
The tabs are not displayed on the page selected in settings page.

The normal editor is still displayed.
It is maybe because "Fusion Builder" is build in the theme.

**Comment by spivurno** [comment]
Hi Lekiend, reach out to us via support and we'll be happy to help.

http://gravitywiz.com/support/
