### ISSUE TITLE
The different views of activation no longer working

### ISSUE THREAD

**Issue by coderesolution** [spivurno/gfur-activate-template#4]
Hello,

Whilst the `activate.php` seems to be working fine, the views (`activate-success.php`, `activate-no-key.php` and `activate-error.php`) files make no difference when edited.

This is odd because I can see that it is getting these files using `get_template_part();` but yet it seems that the default files from `/wp-content/plugins/gravityformsuserregistration/includes/activate.php` are being utilized here instead.

Please, can you advise? Thank you and much appreciated!

**Comment by coderesolution** [comment]
Never mind, as it turns out - I'm stupid!

**Comment by spivurno** [comment]
Appreciate the interaction, regardless!
