### ISSUE TITLE
The views of the activation are not displaying

### ISSUE THREAD

**Issue by omri09** [spivurno/gfur-activate-template#5]
Hello,

The activate.php in '/wp-content/plugins/gravityformsuserregistration/includes/activate.php' seems to be utilized instead of the views in the theme folder 'gfur-activate-template' (activate-success.php, activate-no-key.php and activate-error.php), these files make no difference when edited.

Can you please check it? Thank you in advance.

**Comment by spivurno** [comment]
Did you implement the code to override the default template?

https://gravitywiz.com/customizing-gravity-forms-user-registration-activation-page/#override_default_template
