### ISSUE TITLE
Doesn't work (or not anymore)

### ISSUE THREAD

**Issue by Marc-MMA** [spivurno/gfur-activate-template#6]
Hello,

I think I followed the tutorial to the letter (nothing complex). It just doesn't work, it doesn't do anything.

Does it need to be updated?

Thanks in advance

**Comment by spivurno** [comment]
We've confirmed that this resource is still working as expected for us. It's possible there is a conflict with something on your end or a minor configuration issue. We'd be happy to dig into your specific use case [via support](https://gravitywiz.com/support).
